olin:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_position_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_joint
    pid: {p: 0.0, i: 0.0, d: 0.0}
  right_position_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_joint
    pid: {p: 0.0, i: 0.0, d: 0.0}
